version: '2'
services:
  devfpserver-app:
    image: devfpserver
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://devfpserver-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=devfpserver
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  devfpserver-mongodb:
    extends:
      file: mongodb.yml
      service: devfpserver-mongodb
